import { PlaceHolderImages } from './placeholder-images';
import { mockPayments } from './payment-data';

export const partners = [
  {
    id: 'p-001',
    name: 'Innovate Inc.',
    tier: 'Platinum',
    pais: 'Estados Unidos',
    status: 'Active',
    totalSales: 150000,
    revenue: 75000,
    avatarUrl: PlaceHolderImages.find(p => p.id === 'partner-1')?.imageUrl || '',
    email: 'contact@innovate.com',
    joinDate: '2022-01-15',
  },
  {
    id: 'p-002',
    name: 'Solutions LLC',
    tier: 'Gold',
    pais: 'Reino Unido',
    status: 'Active',
    totalSales: 120000,
    revenue: 60000,
    avatarUrl: PlaceHolderImages.find(p => p.id === 'partner-2')?.imageUrl || '',
    email: 'info@solutions.llc',
    joinDate: '2022-03-20',
  },
  {
    id: 'p-003',
    name: 'Tech Gurus',
    tier: 'Gold',
    pais: 'Japón',
    status: 'Active',
    totalSales: 110000,
    revenue: 55000,
    avatarUrl: PlaceHolderImages.find(p => p.id === 'partner-3')?.imageUrl || '',
    email: 'support@techgurus.io',
    joinDate: '2022-05-10',
  },
  {
    id: 'p-004',
    name: 'Apex Traders',
    tier: 'Silver',
    pais: 'Canadá',
    status: 'Suspended',
    totalSales: 50000,
    revenue: 25000,
    avatarUrl: PlaceHolderImages.find(p => p.id === 'partner-4')?.imageUrl || '',
    email: 'sales@apextraders.com',
    joinDate: '2023-01-05',
  },
  {
    id: 'p-005',
    name: 'Synergy Corp',
    tier: 'Silver',
    pais: 'Brasil',
    status: 'Active',
    totalSales: 80000,
    revenue: 40000,
    avatarUrl: PlaceHolderImages.find(p => p.id === 'partner-5')?.imageUrl || '',
    email: 'partner@synergy.corp',
    joinDate: '2023-02-18',
  },
  {
    id: 'p-006',
    name: 'Growth Partners',
    tier: 'Bronze',
    pais: 'Alemania',
    status: 'Inactive',
    totalSales: 25000,
    revenue: 12500,
    avatarUrl: PlaceHolderImages.find(p => p.id === 'partner-6')?.imageUrl || '',
    email: 'contact@growthpartners.biz',
    joinDate: '2023-08-30',
  },
   {
    id: 'gHZ9n7s2b9X8fJ2kP3s5t8YxVOE2',
    name: 'alexjf',
    tier: 'Platinum',
    pais: 'Colombia',
    status: 'Active',
    totalSales: 250000,
    revenue: 125000,
    avatarUrl: '',
    email: 'alexsuperadmin@gmail.com',
    joinDate: '2021-01-01',
  }
];

export const salesData = [
    { month: 'Jan', totalSales: 4000, subPartnerSales: 2400 },
    { month: 'Feb', totalSales: 3000, subPartnerSales: 1398 },
    { month: 'Mar', totalSales: 5000, subPartnerSales: 7800 },
    { month: 'Apr', totalSales: 2780, subPartnerSales: 3908 },
    { month: 'May', totalSales: 1890, subPartnerSales: 4800 },
    { month: 'Jun', totalSales: 2390, subPartnerSales: 3800 },
    { month: 'Jul', totalSales: 3490, subPartnerSales: 4300 },
    { month: 'Aug', totalSales: 3650, subPartnerSales: 4100 },
    { month: 'Sep', totalSales: 4120, subPartnerSales: 5200 },
    { month: 'Oct', totalSales: 4580, subPartnerSales: 5500 },
    { month: 'Nov', totalSales: 4900, subPartnerSales: 6100 },
    { month: 'Dec', totalSales: 5200, subPartnerSales: 6800 },
  ];

export const payments = mockPayments;
